apiVersion: apps/v1
kind: Deployment
metadata:
  name: care
  labels:
    app: care
spec:
  replicas: 3
  selector:
    matchLabels:
      app: care
  template:
    metadata:
      labels:
        app: care
    spec:
      containers:
      - name: care
        image: 765415433338.dkr.ecr.eu-central-1.amazonaws.com/registry:care
        ports:
        - containerPort: 80