apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: care-certificate
  namespace: default
spec:
  dnsNames:
    - care.med-united.health
  secretName: care-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: care
  labels:
    app: care
spec:
  replicas: 3
  selector:
    matchLabels:
      app: care
  template:
    metadata:
      labels:
        app: care
    spec:
      containers:
      - name: care
        image: 765415433338.dkr.ecr.eu-central-1.amazonaws.com/care:$IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: care
spec:
  selector:
    app: care
  ports:
    - port: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: care
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - care.med-united.health
    secretName: care-tls
  rules:
  - host: care.med-united.health
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: care
              port:
                number: 8080
  
